# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f6838027814581f61accce8fb92051fe355176a2956655f9c4be38f66ea92eeef4e9fae771b126d4232a9d7198e468c4062e7be697359f1b1304357a8bf785

test:
  secret_key_base: e7e6cdf76372d2b0848d0d0fc5a3186cd64711aec8bc383a9c3c0c08142e5bd4bcabd784e65896fd0361c82d1c9d5bd2eac73878749b0257b1882bdb5ee4ba57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
